language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
    - make bootstrap
    - source .env/bin/activate
# service stuff
services:
  - mongodb
# command to run tests
script: make test
# no pesky email notifications
notifications:
  email: false
# setup environment
env:
  - PYTHONPATH="${PYTHONPATH}:${TRAVIS_BUILD_DIR}/ncr/ncr"
after_script:
  coveralls
